---
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/hassio-addons/debian-base/aarch64:6.0.0"
  amd64: "ghcr.io/hassio-addons/debian-base/amd64:6.0.0"
