---
# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Grafana Mimir
version: dev
slug: mimir
description: A scalable storage for prometheus
url: "https://github.com/cedricziel/ha-addon-grafana-mimir/blob/main/mimir"
apparmor: false
ports:
  8001/tcp: null
  9001/tcp: null
ports_description:
  8001/tcp: Mimir
  9001/tcp: gRPC
arch:
  - aarch64
  - amd64
init: false
map:
  - share:rw
homeassistant_api: true
options:
  scrape_ha: false
schema:
  scrape_ha: "bool?"
image: "ghcr.io/cedricziel/ha-addon-grafana-mimir/{arch}"
