# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
ARG BUILD_FROM=ghcr.io/hassio-addons/debian-base/aarch64:6.0.0

# Telelgraf
FROM --platform=linux/amd64 grafana/mimir:2.2.0 as mimir-amd64
FROM --platform=linux/arm64 grafana/mimir:2.2.0 as mimir-arm64

# Agent
FROM --platform=linux/amd64 telegraf:1.24.0 as telegraf-amd64
FROM --platform=linux/arm64/v8 telegraf:1.24.0 as telegraf-arm64

FROM scratch as container

COPY --from=mimir-amd64 /bin/mimir /amd64/
COPY --from=mimir-arm64 /bin/mimir /aarch64/

COPY --from=telegraf-amd64 /usr/bin/telegraf /amd64/
COPY --from=telegraf-arm64 /usr/bin/telegraf /aarch64/

FROM $BUILD_FROM

# Execute during the build of the image
ARG TEMPIO_VERSION BUILD_ARCH
RUN \
    curl -sSLf -o /usr/bin/tempio \
    "https://github.com/home-assistant/tempio/releases/download/${TEMPIO_VERSION}/tempio_${BUILD_ARCH}"

COPY --from=container /${BUILD_ARCH}/mimir /bin/mimir
COPY --from=container /${BUILD_ARCH}/telegraf /bin/telegraf

# Copy root filesystem
COPY rootfs /
